# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(db_index=True, max_length=40, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('type', models.CharField(choices=[('buy', 'Обьявление о продаже клиенту'), ('sell', 'Обьявление о покупке у клиента')], max_length=80, verbose_name='Тип обьявления')),
                ('bank_name', models.CharField(max_length=80)),
                ('account_info', models.TextField()),
                ('msg', models.TextField()),
                ('step', models.IntegerField(verbose_name='Шаг')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='AdAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(choices=[('bank', 'Банки'), ('stop_list', 'Стоп-лист'), ('not_stop_list', 'Не стоп-лист')], max_length=80, verbose_name='Тип')),
                ('attribute_value', models.CharField(max_length=200, verbose_name='Значение')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ключевые_слова', to='webparser.Ad', verbose_name='Обьявление')),
            ],
            options={
                'verbose_name': 'Ключевое слово',
                'verbose_name_plural': 'Ключевые слова',
            },
        ),
    ]
