# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webparser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_id',
            field=models.CharField(db_index=True, max_length=40, verbose_name='ID объявления на localbitcoins'),
        ),
    ]
