# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webparser', '0003_auto_20170422_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='update_time',
            field=models.IntegerField(default=60, verbose_name='Обновлять каждые(сек_'),
            preserve_default=False,
        ),
    ]
