# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webparser', '0004_ad_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='update_time',
        ),
        migrations.AddField(
            model_name='ad',
            name='type_step',
            field=models.CharField(choices=[('percent', 'Проценты от BTC-E'), ('money', 'В рублях от лучшего обьявления')], default='money', max_length=80, verbose_name='Тип обьявления'),
        ),
    ]
