# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webparser', '0006_auto_20170423_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_sell_price', models.CharField(max_length=80)),
                ('best_buy_price', models.CharField(max_length=80)),
                ('btc_e_sell_price', models.CharField(max_length=80)),
                ('btc_e_buy_price', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='ad',
            name='type_step',
            field=models.CharField(choices=[('percent', 'Проценты от BTC-E'), ('money', 'В рублях от лучшего обьявления')], default='money', max_length=80, verbose_name='Тип шага'),
        ),
    ]
