# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webparser', '0007_auto_20170423_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentvalues',
            name='best_buy_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='currentvalues',
            name='best_sell_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='currentvalues',
            name='btc_e_buy_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='currentvalues',
            name='btc_e_sell_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
